service: datamuse-search

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  search:
    handler: main.run
    events:
      - http:
          path: search
          method: get
          integration: lambda
          response:
            headers:
              Content-Type: "'text/plain'"
            template: "$input.path('$')"